[project]
name = "mab-tts"
version = "0.1.0"
description = "TTS (text to speech) tool based on coqui-ai/TTS and Gradio."
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "gradio>=5.16.2",
    "pylint>=3.3.4",
    "tts>=0.22.0",
]
