name: Sync from Github to HuggingFace
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add remote
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: git remote add space https://mbernal84:$HF@huggingface.co/spaces/mbernal84/mab-tts

      - name: Push to hub
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: git push --force https://mbernal84:$HF@huggingface.co/spaces/mbernal84/mab-tts main
